### ISSUE TITLE
Use Angular's $log service instead of console

### ISSUE THREAD

**Issue by jukkakoskinen** [marknutter/firebase-resource#2]
The $log service provides niceties like logging levels, and won't break anything if the console object is not available in the current browser.

Also, provide developers an option to disable logging.

Nice library by the way.

**Comment by jukkakoskinen** [comment]
Same goes for setTimeout (on line 277), you should use the $timeout service instead.

**Comment by marknutter** [comment]
Good call, thanks for the issue!
