### ISSUE TITLE
Errors in the timestamp function

### ISSUE THREAD

**Issue by jukkakoskinen** [marknutter/firebase-resource#3]
The timestamp function gives the following error:

``` javascript
TypeError: Cannot read property 'TIMESTAMP' of undefined
```

Lines 235 and 237 set a timestamp like this:

``` javascript
resource.updated_at = firebase.ServerValue.TIMESTAMP
```

This fails because ServerValue is available on the global Firebase object, not on the reference. So this should work:

``` javascript
resource.updated_at = Firebase.ServerValue.TIMESTAMP
```

**Comment by marknutter** [comment]
Good catch. Reverted that change and moved the mocked objects out into their own file to make sure the test suite continues to pass.
